[package]
name = "credential_truth"
version = "0.0.1"
edition = "2021"
authors = ["Will Burden"]
description = "A Docker Credential Helper depending on pass."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
